FORMAT: 1A
HOST: http://82.196.6.26:3000/

# league

# Group Auth

## login [/login]
### login [POST]
+ Request (application/json)
        {"email": "cousenavi@gmail.com", password: "123"}

+ Response 200 (application/json)
        {"role": "ADMIN"}
    
## logout [/logout]
### logout [GET]
+ Request (application/json)
        
+ Response 200 (application/json)
        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## users [/users]
### users[GET]
+ Request (application/json)
+ Response 200 (application/json)
    [ { _id: 5395d817b170174613f57d27,
    email: 'root@root',
    __v: 0,
    roles: [ 'root' ] }]


## add_user [/users_add]
### add_user [POST]
+ Request (application/json)
        {"email": "cousenavi@gmail.com", password: "123"}
+ Response 200 (application/json)
        {"ok": "ok"}

## update_user [/users_update]
### update_user [POST]
+ Request (application/json)
        {"email": "cousenavi@gmail.com", password: "123"}
+ Response 200 (application/json)
        {"ok": "ok"}

## delete_user [/users_delete]
### delete_user [POST]
+ Request (application/json)
        {"email": "cousenavi@gmail.com", password: "123"}
+ Response 200 (application/json)
        {"ok": "ok"}

# Group Team
## get [/teams/{name}]
### get [GET]
+ Request (application/json)

+ Response 200 (application/json)
    {"team": {_id: "12345", name: "Millwall", league: "championship"}, "players": []}

## get list [/teams]
### get all [GET]
+ Request (application/json)

+ Response 200 (application/json)
    [{_id: "12345", name: "Millwall", league: "premier_league"}]

## add team [/teams_add]
### add team [POST]
+ Request (application/json)
    {name: "Millwall", league: "championship"}
+ Response 200 (application/json)
    "ok"

## update team [/teams_update]
### update team [POST]
+ Request (application/json)
    {"team": {_id: "12345", name: "Millwall", league: "premier_league"}
+ Response 200 (application/json)
    "ok"


## delete team [/teams_delete]
### delete team [POST]
+ Request (application/json)
    {id: "12345"}
+ Response 200 (application/json)
    "ok"
